### ISSUE TITLE
MS8607 not recognized on NANO 33 BLE (mbed)

### ISSUE THREAD

**Issue by ratio-x** [adafruit/Adafruit_MS8607#5]
Adafruit_MS8607 library example sketch running on NANO 33 BLE (mbed) does doesn't recognize the sensor (both pressure and humidity). This is not caused by the Adafruit_MS8607 library, but by the Arduino mbed Wire.cpp implementation of endTransmission. The problem and a workaround is reported here:

https://forum.arduino.cc/t/nano-33-ble-i2c-problems-caused-in-mbed-wire-cpp-read-write-bit-on-i2c-scan/964676

**Comment by ladyada** [comment]
hiya, we use Adafruit_BusIO to do the I2C bus scanning - 
https://github.com/adafruit/Adafruit_BusIO/blob/master/Adafruit_I2CDevice.cpp#L60
so if that isnt going to detect a device the driver wont work. not sure why this issue is opened here: probably better to open it over at the arduino mbed repo?

**Comment by ratio-x** [comment]
The I2C bus scanning definitely does not work with current version of Arduino mbed Wire.cpp.

I opened this issue just to inform about the problem with I2C on mbed platform, in case somebody would report here net being able to connect to MS8607, as in my case.

**Comment by ladyada** [comment]
ok great - however nobody is gonna see it here, because we have 200~ I2C libraries it affects each one. it really needs to be opened over at arduino so it can be fixed :)
